version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: halal_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: halal_user
      POSTGRES_PASSWORD: halal_pass
      POSTGRES_DB: halal_directory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
